export const SET_CANVAS = 'SET_CANVAS';
export const RESIZE_STAGE = 'RESIZE_STAGE';
export const SET_STAGE_SIZE = 'SET_STAGE_SIZE';
export const SELECT_TOOL = 'SELECT_TOOL';
export const SET_ATTRIBUTE = 'SET_ATTRIBUTE';

export const SET_BACKGROUND_IMAGE = 'SET_BACKGROUND_IMAGE';
